### ISSUE TITLE
Write a java program for linear search.

### ISSUE THREAD

**Issue by My-Temp-Github** [My-Temp-Github/Hacktoberfest-Contributions-2023#1]

**Comment by nikitadudhbhate** [comment]
@My-Temp-Github I would like to work on this issue, could you please assign this to me?

**Comment by My-Temp-Github** [comment]
Done @nikitadudhbhate

**Comment by fazil-syed** [comment]
Hi I see no one is assigned to this can you assign this to me?

**Comment by My-Temp-Github** [comment]
@fazil-syed this issue is already assigned to someone. You can open another issue.

**Comment by fazil-syed** [comment]
I see can I contribute to any issue once created?

**Comment by My-Temp-Github** [comment]
@fazil-syed yeah sure.
