### ISSUE TITLE
Write a java program to check armstrong number

### ISSUE THREAD

**Issue by My-Temp-Github** [My-Temp-Github/Hacktoberfest-Contributions-2023#10]
A positive integer is called an Armstrong number of order n if In case of an Armstrong number of 3 digits, the sum of cubes of each digits is equal to the number itself.
 For example:
153 = 1*1*1 + 5*5*5 + 3*3*3  // 153 is an Armstrong number.

**Comment by nikitadudhbhate** [comment]
@My-Temp-Github I would like to work on this issue, could you please assign this to me?

**Comment by My-Temp-Github** [comment]
Done @nikitadudhbhate

**Comment by ArcheR1901** [comment]
Please assign me this

**Comment by My-Temp-Github** [comment]
@ArcheR1901 Its already done you can open another issue.
