### ISSUE TITLE
Write a java program to display fibonacci series

### ISSUE THREAD

**Issue by My-Temp-Github** [My-Temp-Github/Hacktoberfest-Contributions-2023#4]
Write a program in java that should display the fibonacci series 
0 1 1 2 3 5 8 13 21 .......................................

**Comment by nikitadudhbhate** [comment]
@My-Temp-Github I would like to work on this issue, could you please assign this to me?

**Comment by My-Temp-Github** [comment]
Done @nikitadudhbhate
