### ISSUE TITLE
Write a java program to check whether a string is palindrome or not.

### ISSUE THREAD

**Issue by My-Temp-Github** [My-Temp-Github/Hacktoberfest-Contributions-2023#7]
A palindrome is a string which is equal when we read it from front or backward direction.

Ex:
String : madam
Output : true

String : abcbd
Output: false

**Comment by nikitadudhbhate** [comment]
@My-Temp-Github I would like to work on this issue, could you please assign this to me?

**Comment by My-Temp-Github** [comment]
Done @nikitadudhbhate
